title: "Chen Lab"
description: "Genome editing and molecular delivery at Penn Chemistry"
url: "https://kchen90.github.io"
baseurl: "/al-folio"

author:
  name: "Kai Chen"
  email: "kchen90@sas.upenn.edu"
  affiliations:
    - "Department of Chemistry, University of Pennsylvania"

# Add what you have; you can leave others blank
scholar_username: "zvzYKAsAAAAJ"
orcid: "0000-0002-3325-3536"
github_username: "kchen90"
